
package br.com.edumelo.primer.ws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HelloWorldService", targetNamespace = "http://www.jboss.org/eap/quickstarts/wshelloworld/HelloWorld")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHelloToNames", targetNamespace = "http://www.jboss.org/eap/quickstarts/wshelloworld/HelloWorld", className = "br.com.edumelo.primer.ws.client.SayHelloToNames")
    @ResponseWrapper(localName = "sayHelloToNamesResponse", targetNamespace = "http://www.jboss.org/eap/quickstarts/wshelloworld/HelloWorld", className = "br.com.edumelo.primer.ws.client.SayHelloToNamesResponse")
    public String sayHelloToNames(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://www.jboss.org/eap/quickstarts/wshelloworld/HelloWorld", className = "br.com.edumelo.primer.ws.client.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://www.jboss.org/eap/quickstarts/wshelloworld/HelloWorld", className = "br.com.edumelo.primer.ws.client.SayHelloResponse")
    public String sayHello();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHelloToName", targetNamespace = "http://www.jboss.org/eap/quickstarts/wshelloworld/HelloWorld", className = "br.com.edumelo.primer.ws.client.SayHelloToName")
    @ResponseWrapper(localName = "sayHelloToNameResponse", targetNamespace = "http://www.jboss.org/eap/quickstarts/wshelloworld/HelloWorld", className = "br.com.edumelo.primer.ws.client.SayHelloToNameResponse")
    public String sayHelloToName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
