
package br.com.edumelo.primer.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HelloWorldService", targetNamespace = "http://www.jboss.org/eap/quickstarts/wshelloworld/HelloWorld", wsdlLocation = "file:/C:/Softwares/Producao/Java/java-education-primer-wsimport/src/wsdl/HelloWorldService.wsdl")
public class HelloWorldService_Service
    extends Service
{

    private final static URL HELLOWORLDSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.com.edumelo.primer.ws.client.HelloWorldService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.com.edumelo.primer.ws.client.HelloWorldService_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Softwares/Producao/Java/java-education-primer-wsimport/src/wsdl/HelloWorldService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Softwares/Producao/Java/java-education-primer-wsimport/src/wsdl/HelloWorldService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HELLOWORLDSERVICE_WSDL_LOCATION = url;
    }

    public HelloWorldService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldService_Service() {
        super(HELLOWORLDSERVICE_WSDL_LOCATION, new QName("http://www.jboss.org/eap/quickstarts/wshelloworld/HelloWorld", "HelloWorldService"));
    }

    /**
     * 
     * @return
     *     returns HelloWorldService
     */
    @WebEndpoint(name = "HelloWorld")
    public HelloWorldService getHelloWorld() {
        return super.getPort(new QName("http://www.jboss.org/eap/quickstarts/wshelloworld/HelloWorld", "HelloWorld"), HelloWorldService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldService
     */
    @WebEndpoint(name = "HelloWorld")
    public HelloWorldService getHelloWorld(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.jboss.org/eap/quickstarts/wshelloworld/HelloWorld", "HelloWorld"), HelloWorldService.class, features);
    }

}
